### ISSUE TITLE
Migrate to ML-Agents v0.6

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/marathon-envs#10]
Migrate MarathonEnv to work with ML-Agents v0.6

Follow migration docs - https://github.com/Unity-Technologies/ml-agents/blob/release-v0.6/docs/Migrating.md

Retrain brains

**Comment by Sohojoe** [comment]
@awjuliani is v0.6 mature enough to start the migration or should I wait for a little while?

**Comment by awjuliani** [comment]
Hi @Sohojoe,

v0.6 is code-frozen expect for bug-fixes right now. As such, you should be fine to use the `release-v0.6` branch and re-train the models based on that.

**Comment by Sohojoe** [comment]
@awjuliani - How do I set up the new Inference Engine / TensorFlowSharp? The docs make references to Inference-Engine.md but I don't see that file in the [release-v0.](https://github.com/Unity-Technologies/ml-agents/tree/release-v0.6) branch

**Comment by awjuliani** [comment]
This is the one "catch," which is that we are using a new inference solution for v0.6, and it isn't ready for public release just yet. It should be ready for release in the next couple weeks though.

**Comment by Sohojoe** [comment]
Makes sense - will the v0.6 examples work with the v0.5 inference / tensorflow sharp?

**Comment by Sohojoe** [comment]
@awjuliani - do you have an update on the inference engine? I saw [release-v0.6-revertTF1](
https://github.com/Unity-Technologies/ml-agents/tree/release-v0.6-revertTF1) and wondered if you are reverting to TensorFlowSharp for v0.6?

**Comment by awjuliani** [comment]
@Sohojoe That is right. We decided to keep TF# for v0.6, and will be moving to our internal inference solution for a later version.
