### ISSUE TITLE
Parse Issue - marathon-envs

### ISSUE THREAD

**Issue by F-Brar** [Unity-Technologies/marathon-envs#15]
@Sohojoe 

i am having problems, getting the marathon-envs to work. I just wanted to check if this is a known issue, or if i am doing something wrong.

When i try to start any of the deepmind scenes, i get the following error message:

```
FormatException: Input string was not in a correct format.
System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
```
I am using Unity version 2018.2.14f1. I tried using both the original marathon-envs repo ml-agents v0.5 and the ActiveRagdollAssaultCourse repo.

Here is the detailed console output for the DeepMindHumanoid scene:

```
FormatException: Input string was not in a correct format.
System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
System.Single.Parse (System.String s) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
MLAgents.MarathonSpawner.ParseCompilerOptions (System.Xml.Linq.XElement xdoc) (at Assets/MarathonEnvs/Scripts/MarathonSpawner.cs:205)
MLAgents.MarathonSpawner.Parse () (at Assets/MarathonEnvs/Scripts/MarathonSpawner.cs:100)
MLAgents.MarathonSpawner.SpawnFromXml () (at Assets/MarathonEnvs/Scripts/MarathonSpawner.cs:56)
MLAgents.MarathonAgent.AgentReset () (at Assets/MarathonEnvs/Scripts/MarathonAgent.cs:145)
DeepMindHumanoidAgent.AgentReset () (at Assets/MarathonEnvs/Enviroments/DeepMindHumanoid/Scripts/DeepMindHumanoidAgent.cs:13)
MLAgents.Agent._AgentReset () (at Assets/ML-Agents/Scripts/Agent.cs:742)
MLAgents.Academy.ForcedFullReset () (at Assets/ML-Agents/Scripts/Academy.cs:519)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:562)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:610)
```
Sorry if this is a trivial question, I am not a coder.
Thanks a lot for sharing this!

**Comment by F-Brar** [comment]
Thanks for the quick answer! 
I was able to start all ml-agents scenes from the beginning. 
Unfortunately i am getting the same error in the QuickStart project (wich i haven't tested before ). 
I am on Windows 10. I will run more tests in another unity version later.

**Comment by F-Brar** [comment]
@Sohojoe 
Do you have any idea what might cause the issue and how to solve it?
Thank you.

**Comment by Sohojoe** [comment]
@F-Brar  - I belive the problem is that I don't properly deal with globalization during the xml parsing. I'm guessing that your windows machine is set to none US-English. Its hard for me to reproduce locally but I have made a stab at fix in this [gist](https://gist.github.com/Sohojoe/5948d51a8e04ebbb4a426452412038ad) - can you try swapping out your local MarathonSpawner.cs

if you are still having problems: something that may help us track it down is by turning on **Debug Output** in one of the agents 
<img width="205" alt="image" src="https://user-images.githubusercontent.com/4400544/48595576-1e2cd700-e90a-11e8-8707-779274fe2854.png">

**Comment by F-Brar** [comment]
@Sohojoe 
Thank you very much! The fix works :)
