### ISSUE TITLE
Training on ubuntu

### ISSUE THREAD

**Issue by vivanov879** [Unity-Technologies/marathon-envs#26]
Hi. I git cloned the repo, ran via Unity SDK, and it makes back flips well. In the Training.md, it says: 
`Download the correct version of MarathonEnvs for your platform and put it in the envs\ folder`
What do I download for Ubuntu and put there?

**Comment by Sohojoe** [comment]
@vivanov879  - you can download them from the Releases - [here](https://github.com/Unity-Technologies/marathon-envs/releases/tag/v2.0.0-alpha.2). I have not tested it on linux but it should work.

Note download saves you building from Unity - if you want to customize (change the animation) then you will need to build a custom version

the command line should look something like this:- `mlagents-learn config/marathon_envs_config.yaml --train --env="envs/MarathonEnvs/Unity Environment.x86_64" --num-envs=10 --run-id=TerrainMarathonMan401 --env-args --spawn-env=TerrainMarathonMan-v0 --num-spawn-envs=100`

See [here](https://github.com/Unity-Technologies/marathon-envs/blob/master/Training.md) for more on the command line for training

**Comment by vivanov879** [comment]
@Sohojoe Joe, thanks for sharing the tips. I was able to start training the Marathon Man Backflip agent. On a quick note, the Training.md instructions were missing the details for the Backfilp, I created a merge request.

As for adding my own environments: Is the `UnityEnvironment.x86_64` simply a build of `UnitySDK` project in the root directory of the `marathon-envs/` project? Then, to update an environment, I need to 
- open the Project in `UnitySDK/` directory
- make changes to the agents, Animations, terrain, or `Style Transfer Animation.cs` Script
- Select `Project->Build` to build a Linux executable of the Project
- place the executable into the `envs/MarathonEnvs/Unity Environment.x86_64` directory

**Comment by vivanov879** [comment]
@Sohojoe Joe, what does the sensor Distance mean? The distances calculated from various body parts make sense to me, but this doesn't:
```
			var sensorDistance = 0.0;
			var sensorDistanceStep = 1.0 / _agent.SensorIsInTouch.Count;
			for (int i = 0; i < _agent.SensorIsInTouch.Count; i++)
			{
				if (animStep.SensorIsInTouch[i] != _agent.SensorIsInTouch[i])
					sensorDistance += sensorDistanceStep;
			}
```
