### ISSUE TITLE
Buffer size

### ISSUE THREAD

**Issue by vivanov879** [Unity-Technologies/marathon-envs#28]
Hi. Can you please clarify couple issues for me? Where does `28` come from in configuration file? I guess this is just some hyperparameter to tune. 
```
    buffer_size: 21504 # 768 * 28
```

what about this line in BodyPart.cs: 
```
        angularVelocity /= 128f;
```
is `128` simply a constant which can be treated as a hyperparameter?

**Comment by Sohojoe** [comment]
The 28 came from doing a hyperparamter search - the number of concurrent agents I train with is quite aggressive and can make training less stable, but I wanted to see how far I could push it. I have some training info on the [discord channel](https://discordapp.com/channels/667120422621413400/667121041767792660/672878888153645115) 

The 128, I can't remember how I arrived at this number.
