### ISSUE TITLE
Style Transfer Animation bug

### ISSUE THREAD

**Issue by vivanov879** [Unity-Technologies/marathon-envs#29]
Hi. When running the Backflip Environment, if you press pause on the unity editor control panel, and step forward frame by frame, you will see the the animator starts to rotate at a high speed when at the top point of the backflip. I haven't root caused the issue yet. I think it has something to do with rotation wrongly applied to the animator Object. 

Update: 
I fixed that by enabling "Bake into Pose" in the animation controller. The animation is well behaved now.

**Comment by Sohojoe** [comment]
Hi @vivanov879 - that is great you figured out the cause - I had seen this issue and but had not been able to figure out the root cause.
