### ISSUE TITLE
Error:To use dlopen, you need to use Emscripten's linking support,

### ISSUE THREAD

**Issue by daniellibin** [Unity-Technologies/marathon-envs#44]
When I use mujoco's Unity Plugin (http://www.mujoco.org/book/unity.html#Gaming) to build a webgl project, the following error appears:
`To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking
printErr @ scene_web.loader.js:31
abort @ scene_web.framework.js:14
_dlopen @ scene_web.framework.js:8920
__ZN6il2cpp2osL19LoadLibraryWithNameEPKci @ scene_web.wasm:1
__ZN6il2cpp2os13LibraryLoader22LoadDynamicLibraryImplERKNS_5utils10StringViewIcEEi @ scene_web.wasm:1
__ZN6il2cpp2os13LibraryLoader22LoadDynamicLibraryImplERKNS_5utils10StringViewIcEE @ scene_web.wasm:1
__ZN6il2cpp2os13LibraryLoader18LoadDynamicLibraryENS_5utils10StringViewIcEEi @ scene_web.wasm:1
__ZN6il2cpp2os13LibraryLoader18LoadDynamicLibraryENS_5utils10StringViewIcEE @ scene_web.wasm:1
__ZN6il2cpp2vm14PlatformInvoke7ResolveERK16PInvokeArguments @ scene_web.wasm:1
__Z22il2cpp_codegen_resolveRK16PInvokeArguments @ scene_web.wasm:1
__Z30il2cpp_codegen_resolve_pinvokeIPFivELm12ELm15EET_RAT0__KcRAT1__S3_20Il2CppCallConvention13Il2CppCharSetib @ scene_web.wasm:1
_MJP_mjp_initialize_m499C5BFB3237988EC9E8E6944F0C2ACEA26F16B7 @ scene_web.wasm:1
_MJP_Initialize_m645E8252176D721BDFDA0596CA389E37DFBECB1C @ scene_web.wasm:1
_MJSimulate_Start_m4252A207F9335502481C9CD886361DF47FDA434F @ scene_web.wasm:1
__Z65RuntimeInvoker_TrueVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5PFvvEPK10MethodInfoPvPS4_ @ scene_web.wasm:1
dynCall_iiiii @ scene_web.wasm:1
(anonymous) @ scene_web.framework.js:24365
invoke_iiiii @ scene_web.framework.js:15899
__ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException @ scene_web.wasm:1
_il2cpp_runtime_invoke @ scene_web.wasm:1
__Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb @ scene_web.wasm:1
__ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb @ scene_web.wasm:1
__ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtrP21ScriptingExceptionPtr @ scene_web.wasm:1
__ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtr @ scene_web.wasm:1
__ZN13MonoBehaviour16DelayedStartCallEP6ObjectPv @ scene_web.wasm:1
__ZN18DelayedCallManager6UpdateEi @ scene_web.wasm:1
__ZZ23InitPlayerLoopCallbacksvEN50EarlyUpdateScriptRunDelayedStartupFrameRegistrator7ForwardEv @ scene_web.wasm:1
......
scene_web.framework.js:3319 DllNotFoundException: Unable to load DLL 'mjplugin155': The specified module could not be found.
 `

How should I solve it?
But why the demo can work on web?
https://github.com/Unity-Technologies/marathon-envs/tree/v3.0.0

Thanks

**Comment by Sohojoe** [comment]
Hi @daniellibin  - MarathonEnvs does not use mujoco. It uses the physics engine built into Unity (PhysX). You should ask mujoco support, it maybe they don't support webgl
