### ISSUE TITLE
Does the marathon-envs gym wrapper work with Stable Baselines?

### ISSUE THREAD

**Issue by gwalter98** [Unity-Technologies/marathon-envs#46]
Hi,

I was very excited to discover this repository and wanted to see if I could get the environments to work with Stable Baselines. 

I noticed that there is a gym wrapper for the marathon envs and also a file called 'stable_baselines_sac_train.py'. However, when I try to run this file I get the following error:

Traceback (most recent call last):
  File "stable_baselines_sac_train.py", line 30, in <module>
    model.learn(total_timesteps=50000, log_interval=10)
  File "D:\Anaconda3\envs\project\lib\site-packages\stable_baselines\sac\sac.py", line 410, in learn
    new_obs, reward, done, info = self.env.step(unscaled_action)
  File "D:\Anaconda3\envs\project\lib\site-packages\marathon_envs\envs\__init__.py", line 240, in step
    self._n_agents
marathon_envs.envs.MarathonEnvsException: The environment was expecting a list of 1 actions.
INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).

I thought I might have done something wrong but I then noticed #23 where supporting Stable Baselines was added as a milestone. Am I correct then in believing these environments won't currently work with Stable Baselines?

Any help or advice would be greatly appreciated!

**Comment by Sohojoe** [comment]
Hi @GWALTER4, 

it was working but doesn't have great documentation. Have you downloaded the marathon-env environment? see [releases](https://github.com/Unity-Technologies/marathon-envs/releases/tag/v3.0.0) and put the version you need in the envs folder.

Let me know how I can support you. The notifications are not great from GitHub, so you can aways ping me in the discord channel

**Comment by gwalter98** [comment]
Hi,

Thanks for the reply. Unfortunately, I've had to move to using a different set of environments for the project I'm working on. I may come back to using these in the future though so I'll be sure to join the discord if I have any further issues!

Many thanks!
