### ISSUE TITLE
I forgot the config / trainer_config.yaml

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/marathon-envs#7]
Hey @awjuliani - I realized I did not add the config / hyperparms - I'll dig them up and make a PR - any preference on where it should go? I'm thinking of adding a config/trainer_config.yaml within this repro

**Comment by awjuliani** [comment]
Hey Joe,

`config/trainer_config.yaml` sounds good to me!

**Comment by Sohojoe** [comment]
i used `config\marathon_envs_config.yaml` as it made more sense vs overwriting the ML-Agents `trainer_config.yaml` or using a different folder - #9
